Remove provider.tf
Azure/terraform-azurerm-avm-res-edge-site pull request #5
Opened 2024-07-18 05:59 UTC by xhy8759

## Description

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-07-18 06:27 UTC, duzitong approved these changes

2024-07-31 22:16 UTC, mbilalamjad approved these changes

2024-07-31 22:17 UTC, mbilalamjad commented on README.md
> +# terraform-azapi-avm-ptn-site-manager
Please correct the name ot terraform-azurerm-avm-res-edge-site

2024-07-31 22:18 UTC, mbilalamjad commented on README.md
> -> [!IMPORTANT]
Please do not remove this IMPORTANT notice

2024-07-31 22:18 UTC, mbilalamjad commented on _header.md
> +# terraform-azapi-avm-ptn-site-manager
Please correct the name ot terraform-azurerm-avm-res-edge-site

2024-07-31 22:18 UTC, mbilalamjad commented on _header.md
> -> [!IMPORTANT]
Please do not remove this IMPORTANT notice

2024-07-31 22:20 UTC, mbilalamjad requested changes
Please address the comments

2024-08-02 02:34 UTC, mbilalamjad approved these changes

2024-08-02 02:54 UTC, merged